#!/bin/bash

PRO=$1

if [ -z $PRO ]; then
 echo "Usage $0 <project_name>"
 exit
fi

ping -c 3 $PRO.pro.ailove.ru >/dev/null 2>&1
if [ $? -gt 0 ]; then
  echo "Ping: Unknown host $PRO.pro.ailove.ru"
  exit
fi

rm -rf /tmp/$PRO
mkdir -p /tmp/$PRO
scp -o StrictHostKeyChecking=no  svn@$PRO.pro.ailove.ru:/srv/www/$PRO/conf/database /tmp/$PRO/database > /dev/null
if [ -f /tmp/$PRO/database ]; then
  DB_HOST=`sed -e '/DB_HOST/!d' -e 's/DB_HOST = //' /tmp/$PRO/database`
  DB_NAME=`sed -e '/DB_NAME/!d' -e 's/DB_NAME = //' /tmp/$PRO/database`
  DB_USER=`sed -e '/DB_USER/!d' -e 's/DB_USER = //' /tmp/$PRO/database`
  DB_PASSWORD=`sed -e '/DB_PASSWORD/!d' -e 's/DB_PASSWORD = //' /tmp/$PRO/database`
else
  echo "No config file: /srv/www/$PRO/conf/database"
  exit
fi

if [ "$DB_HOST" == "localhost" ]; then
  scp svn@$PRO.pro.ailove.ru:/etc/pgbouncer.ini /tmp/$PRO/pgbouncer.ini > /dev/null
  if [ ! -f /tmp/$PRO/pgbouncer.ini ]; then
    scp svn@$PRO.pro.ailove.ru:/etc/pgbouncer/pgbouncer.ini /tmp/$PRO/pgbouncer.ini > /dev/null
  fi
  if [ -f /tmp/$PRO/pgbouncer.ini ]; then
    DB_HOST=""
    DB_HOST=`sed -e '/'$DB_NAME'\s*=\s*host=.*/!d' -e 's/'$DB_NAME'\s*=\s*host=//' /tmp/$PRO/pgbouncer.ini`
    if [ -z $DB_HOST ]; then
     DB_HOST=`sed -e  '/^\*\s*=\s*host=.*/!d' -e 's/^\*\s*=\s*host=//' /tmp/$PRO/pgbouncer.ini`
    fi
  else
    DB_HOST=$PRO.pro.ailove.ru
  fi
fi

echo $DB_HOST
echo $DB_NAME
echo $DB_USER
echo $DB_PASSWORD

DDD=`date +%F`
DDDW=`date +%V.%F`

scp -o StrictHostKeyChecking=no  svn@$DB_HOST:/var/backups/mysql/daily/$DB_NAME/${DB_NAME}_$DDD* /tmp/$PRO/mysql.sql.bz2 >/dev/null 2>&1
scp -o StrictHostKeyChecking=no  svn@$DB_HOST:/var/backups/mysql/weekly/$DB_NAME/${DB_NAME}_week.$DDDW* /tmp/$PRO/mysql.sql.bz2 >/dev/null 2>&1
scp -o StrictHostKeyChecking=no  svn@$DB_HOST:/var/backups/mysql/monthly/$DB_NAME/${DB_NAME}_$DDD* /tmp/$PRO/mysql.sql.bz2 >/dev/null 2>&1

scp -o StrictHostKeyChecking=no  svn@$DB_HOST:/var/backups/postgresql/daily/$DB_NAME/${DB_NAME}_$DDD* /tmp/$PRO/pgsql.sql.bz2 >/dev/null 2>&1
scp -o StrictHostKeyChecking=no  svn@$DB_HOST:/var/backups/postgresql/weekly/$DB_NAME/${DB_NAME}_week.$DDDW* /tmp/$PRO/pgsql.sql.bz2 >/dev/null 2>&1
scp -o StrictHostKeyChecking=no  svn@$DB_HOST:/var/backups/postgresql/monthly/$DB_NAME/${DB_NAME}_$DDD* /tmp/$PRO/pgsql.sql.bz2 >/dev/null 2>&1

if [ -f /tmp/$PRO/pgsql.sql.bz2 ]; then
  ## Create pgsql database
  echo "select pg_terminate_backend(procpid) from pg_stat_activity where datname='$DB_NAME'" | psql -U postgres
  dropdb --username=postgres $DB_NAME
  dropuser --username=postgres $DB_USER
  createuser --username=postgres --no-superuser --no-createdb --no-createrole --encrypted $DB_USER
  createdb --username=postgres --encoding=utf-8 --template=template0 --owner=$DB_USER $DB_NAME
  psql --username=postgres --dbname=postgres --command="ALTER USER \"$DB_USER\" WITH ENCRYPTED PASSWORD '$DB_PASSWORD'"
  bzcat /tmp/$PRO/pgsql.sql.bz2 | PGPASSWORD=$DB_PASSWORD psql -U $DB_USER $DB_NAME #> /dev/null 2>&1
  echo "Result code:  $?"
fi

if [ -f /tmp/$PRO/mysql.sql.bz2 ]; then
  ## Create mysql database
  cat << EOF | mysql -f --default-character-set=utf8 -u root -pR5pd1I6t
  DROP USER '$DB_USER';
  DROP DATABASE '$DB_NAME';
  CREATE USER '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD';
  CREATE USER '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD';
  GRANT USAGE ON *.* TO '$DB_USER'@'localhost' IDENTIFIED BY '$DB_PASSWORD' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
  GRANT USAGE ON *.* TO '$DB_USER'@'%' IDENTIFIED BY '$DB_PASSWORD' WITH MAX_QUERIES_PER_HOUR 0 MAX_CONNECTIONS_PER_HOUR 0 MAX_UPDATES_PER_HOUR 0 MAX_USER_CONNECTIONS 0;
  CREATE DATABASE IF NOT EXISTS \`$DB_NAME\`;
  GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'localhost';
  GRANT ALL PRIVILEGES ON \`$DB_NAME\`.* TO '$DB_USER'@'%';
  ALTER DATABASE \`$DB_NAME\` DEFAULT CHARACTER SET utf8 COLLATE utf8_general_ci;
EOF
  bzcat /tmp/$PRO/mysql.sql.bz2 | mysql -u $DB_USER -p$DB_PASSWORD $DB_NAME #> /dev/null 2>&1
  echo "Result code:  $?"
fi

rm -rf /tmp/$PRO
